spring:
  thymeleaf.cache: false
  application:
    name: "productpage"

management:
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    export.prometheus.enabled: true
    tags.application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
server.port: 8099

services:
  review:
    name: localhost
    domain: ""
    port: 9081
    path: reviews
  detail:
    name: localhost
    domain: ""
    port: 9083
    path: details
  rating:
    name: localhost
    domain: ""
    port: 9082
    path: ratings