spring:
  thymeleaf.cache: false
  application:
    name: "productpage"

management:
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    export.prometheus.enabled: true
    tags.application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
server.port: 8099

services:
  review:
    name: reviews
    domain: ""
    port: 9080
    path: reviews
  detail:
    name: details
    domain: ""
    port: 9080
    path: details
  rating:
    name: ratings
    domain: ""
    port: 9080
    path: ratings