apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - productpage.yaml
  - bookinfo-gateway.yaml
configMapGenerator:
  - name: productpage-config
    files:
      - application.yaml